name: "Spack Build-Cache"
description: "Install via Spack, push buildcache to a mirror"
branding:
  icon: package
  color: purple

inputs:
  environment:
    description: "Path to use as the environment"
    required: true
    default: ".spack/default"

  load-environment:
    description: "Whether to automatically load the environment for subsequent steps"
    required: false
    default: "true"

  spack-path:
    description: "Path to install Spack to"
    required: false
    default: "spack"

  token:
    description: "The GitHub token. This will be used to push to the build cache."
    required: false
    default: "${{ github.token }}"

runs:
  using: composite
  steps:
    - name: Configure Spack
      shell: bash
      run: |
        . "${{ inputs.spack-path }}/share/spack/setup-env.sh"
        spack bootstrap now

        spack \
          mirror add \
          --scope site \
          --unsigned \
          --oci-username ${{ github.repository_owner }} \
          --oci-password ${{ inputs.token }} \
          buildcache-numpex \
          oci://ghcr.io/${{ github.repository }}

        spack compiler find --scope site

        # Sane defaults
        spack config --scope site add config:install_tree:root:/opt/root
        spack config --scope site add config:install_tree:padded_length:128

    - name: Install Spack environment
      shell: bash
      run: |
        . "${{ inputs.spack-path }}/share/spack/setup-env.sh"
        spack -e "${{ inputs.environment }}" install

    - name: Automatically load environment
      if: ${{ inputs.load-environment == 'true' }}
      shell: bash
      run: |
        . "${{ inputs.spack-path }}/share/spack/setup-env.sh"
        env_file="/tmp/spack-env"
        spack env activate "${{ inputs.environment }}" --sh > "$env_file"
        while IFS= read -r line; do
          if [[ "$line" =~ ^export\ (.*)=(.*)\;$ ]]; then
            exporting="${BASH_REMATCH[1]}=${BASH_REMATCH[2]}"
            echo ":: exporting $exporting"
            echo "$exporting" >> "$GITHUB_ENV"
          fi
        done < "$env_file"
        rm -f "$env_file"

    - name: Push to cache
      uses: gacts/run-and-post-run@v1
      with:
        post: |
          . "${{ inputs.spack-path }}/share/spack/setup-env.sh"
          spack -e "${{ inputs.environment }}" buildcache \
            push \
            --update-index \
            --with-build-dependencies \
            buildcache-numpex
