name: Test Spack Build-Cache Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  spack_env: .spack/default

jobs:
  smoke:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Spack Build-Cache
        uses: ./
        with:
          environment: ${{ env.spack_env }}

      - name: Check specs
        run: |
          spack -e $spack_env find

      - name: Check programs
        run: |
          spack env activate $spack_env
          which -a cmake
