name: Test Spack Build-Cache Action

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Spack
        uses: spack/setup-spack@v2

      # - name: Add spack.numpex
      #   uses: viperML/spack-repo-action@master
      #   with:
      #     repository: numpex/spack.numpex

      - name: Activate Spack build cache
        uses: ./
        with:
          environment: .spack/default
          base-image: ubuntu:24.04

      - name: Check specs
        run: |
          spack spec

      - name: Check programs
        run: |
          which -a cmake
